#!/bin/sh

dmenu_notas=$HOME/documentos/$(ls -X -r $HOME/documentos/ | dmenu -l 35 -h 20 -c -cw 10)
echo "$dmenu_notas"
[ "$dmenu_notas" = "$HOME/documentos/" ] && exit

[ "$(echo "${dmenu_notas##*.}")" = "pdf" ] && firefox "$dmenu_notas" && exit
[ "$(echo "${dmenu_notas##*.}")" = "png" ] && sxiv "$dmenu_notas" && exit
[ "$(echo "${dmenu_notas##*.}")" = "jpg" ] && sxiv "$dmenu_notas" && exit
st -e nvim "$dmenu_notas"
