#!/bin/sh
browser="qutebrowser"

case "$1" in
    importante)
        favoritos="$HOME/suckless/dmenu/menus/listas/importante"
        ;;
    *)
        favoritos="$HOME/suckless/dmenu/menus/listas/favoritos"
        ;;
esac

selecionado=$(cut -d';' -f1 "$favoritos" | dmenu -l 33 -h 20 -g 4)
[ -z "$selecionado" ] && exit 0 # Sai caso nada seja selecionado
link=$(grep "$selecionado" "$favoritos" | cut -d';' -f2)
$browser "$link" && notify-send "Abrindo no $browser" "$link"
