#!/bin/sh

case "$(printf " Programas\\n Firefox\\nﱮ Ranger\\n Clipboard\\n💀 Kill\\n Printscreen\\n😂 Emojis\\n﫭 Desmontar/montar\\n襤 Energia" | dmenu -l 35 -c -z 300)" in
    " Programas") dmenu_programas ;;
    " Firefox") dmenu_favoritos ;;
    "ﱮ Ranger") st ranger ;;
    " Clipboard") dmenu_clip ;;
    "💀 Kill") dmenu_kill ;;
    " Printscreen") dmenu_print ;;
    "😂 Emojis") dmenu_emoji ;;
    "﫭 Desmontar/montar") dmenu_mont ;;
    "襤 Energia") dmenu_sys ;;
esac