#!/bin/bash

tocando=$(deadbeef --nowplaying-tf '%filename%')
volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))

case "$(printf "玲\\n\\n怜\\n\\n墳 $volume%" | dmenu -h 30 -g 5 -y 350 -z 1360 -n 1 -p "$tocando")" in
    "玲") deadbeef --prev ;;
    "") deadbeef --play-pause ;;
    "怜") deadbeef --next ;;
    "") deadbeef --quit ;;
esac
