#!/bin/sh

chosen=$(cut -d ';' -f1 $HOME/suckless/dmenu/menus/listas/emojis | dmenu -l 35 -h 20 | sed "s/ .*//")

# Sai caso nenhum é selecionado.
[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copiado." &
    xdotool type --window "$window_id" "$chosen"
fi
