#!/bin/sh

case "$(printf " Programas\\n Sudo\\n🫖 Geany\\n Gimp\\n Calculadora\\n Telegram\\n Fluxgui\\n Mpv\\n Transmission\\n Code\\n Discord" | dmenu -l 35 -h 20 -c -cw 200 )" in
    " Programas") dmenu_run ;;
	" Sudo") dmenu_sudo ;;
	"🫖 Geany") geany ;;
	" Gimp") gimp ;;
	" Calculadora") galculator ;;
	" Telegram") telegram-desktop ;;
	" Fluxgui") fluxgui ;;
	" Mpv") mpv ;;
	" Transmission") transmission-gtk ;;
	" Code") code ;;
	" Discord") discord ;;
esac
