#!/bin/sh

abrir() {
    notify-send qutebrowser "Abrindo no qutebrowser\n$link"
    qutebrowser "$link"
}

seleciona_favorito() {
    selecionado=$(printf "%s\n" "$favoritos" | cut -d ';' -f1 | dmenu -l 35 -g 4 -h 20)
    [ -z "$selecionado" ] && exit 0
    link=$(printf "%s" "$favoritos)" | grep -F "$selecionado" | cut -d ';' -f2)
}

case "$1" in
    importante)
        favoritos=$(cat "$HOME/suckless/dmenu/menus/listas/importante")
        seleciona_favorito
        abrir "$link"
        ;;
    *)
        favoritos=$(cat "$HOME/suckless/dmenu/menus/listas/favoritos")
        seleciona_favorito
        abrir "$link"
        ;;
esac
