#!/bin/sh

texto=$(echo "?" | dmenu)
linhas=$(echo "$texto" | wc -c)
if [ "$linhas" -gt 30 ] ; then
    traducao=$(echo "$texto" | trans -b > "$HOME/.cache/translation")
    st -e less $HOME/.cache/translation
else
    traducao=$(echo "$texto" | trans -b) && notify-send Tradução "$traducao"
fi
