#!/bin/sh

selecionado=$(cut -d ';' -f1 "$HOME/suckless/dmenu/menus/listas/emojis" | dmenu -l 35 -h 20 | sed "s/ .*//")

# Sai caso nenhum é selecionado.
[ -z "$selecionado" ] && exit

if [ -n "$1" ]; then
	xdotool type "$selecionado"
else
	printf "%s" "$selecionado" | xclip -selection clipboard
	notify-send -i emoji "'$selecionado' copiado." &
    xdotool type --window "$window_id" "$chosen"
fi
