#!/bin/sh

data=$(date +'%A %d/%m/%Y - %H:%M')

case "$(printf " Programas\\n Copiado\\n❕ Importante\\n Favoritos\\n Notas\\n Histórico\\n韛 Corretor\\n韛 Tradutor\\n Manpages\\n😂 Emojis\\n Print\\n VMs\\n﫭 Des/Montar\\n Wifi\\n❔ Teclas" | dmenu -l 5 -g 3 -h 20 -c -cw 500 -p "$data")" in
    " Programas") dmenu_run ;;
    " Copiado") dmenu_clip ;;
    "❕ Importante") dmenu_favoritos importante ;;
    " Favoritos") dmenu_favoritos ;;
    " Notas") dmenu_notas ;;
    " Histórico") dmenu_shhistory ;;
    "韛 Corretor") dmenu_corretor ;;
    "韛 Tradutor") dmenu_tradutor ;;
    " Manpages") dmenu_man ;;
    "😂 Emojis") dmenu_emoji ;;
    " Print") dmenu_print ;;
    " VMs") dmenu_virtualbox ;;
    "﫭 Des/Montar") dmenu_mont ;;
    " Wifi") dmenu_wifi ;;
    "❔ Teclas") sxhkd_atalhos ;;
esac
