#!/bin/sh

texto=$(echo "" | dmenu -c)
[ -z "$texto" ] && exit 0 # Sai caso não haja nada para traduzir
linhas=$(echo "$texto" | wc -c)
if [ "$linhas" -gt 30 ] ; then
    traducao=$(echo "$texto" | trans -b > "$HOME/.cache/translation")
    st -e less $HOME/.cache/translation
else
    traducao=$(echo "$texto" | trans -b) && notify-send Tradução "$traducao" && \
    echo "$traducao" | xclip -selection clipboard && \
    xdotool type --window "$window_id" "$traducao"
fi
