#!/bin/sh

lista="/home/lucas/suckless/dmenu/menus/listas/editar"
selecionado=$(cut -d';' -f1 "$lista" | dmenu -l 22 -g 2 -h 20 -c -cw 600)
[ -z "$selecionado" ] && exit 0 # Sai caso nada seja selecionado
arquivo=$(grep -m 1 "$selecionado" "$lista" | cut -d';' -f2)
st -e nvim "$arquivo"
