#!/bin/sh

# config
search_url="https://www.google.com/search?q="
open_in_browser="abre_links.sh"
bookmarks_file="$HOME/suckless/dmenu/menus/listas/favoritos"

select_bookmark() {
    bookmarks=$(cat "$bookmarks_file")
    select=$(printf "%s\n" "$bookmarks" \
        | cut -d ';' -f1 \
        | dmenu -l 35 -g 4 -h 20 \
    )

    [ -z "$select" ] \
        && exit 0
    
    open=$(printf "%s" "$bookmarks)" \
        | grep -F "$select" \
        | cut -d ';' -f2 \
    )
    
    [ -z "$open" ] \
        && open=$(printf "%s" "$search_url$select" \
            | sed 's/ /\%20/g' \
        )
}

case "$1" in
    importante)
        bookmarks_file="$HOME/suckless/dmenu/menus/listas/importante"
        select_bookmark
        $open_in_browser "$open"
        ;;
    *)
        select_bookmark
        $open_in_browser "$open"
        ;;
esac
