#!/bin/sh

case "$(printf "ﱮ Ranger\\n🫖 Geany\\n💀 Kill" | dmenu -l 35 -h 20 -c -cw 10 -p "Sudo")" in
    "ﱮ Ranger") st -e sudo ranger ;;
	"🫖 Geany") st -e sudo geany ;;
	"💀 Kill") st -e sudo killmenu ;;
esac
