#!/bin/sh
lingua=$(printf "pt_BR\\nen_US" | dmenu -c)
palavra=$(echo "?" | dmenu -c)

if [ -n "$palavra" ] && [ "$palavra" != "?" ]; then
	selecao=$(echo "$palavra" | aspell pipe -l "$lingua" --suggest | sed -e '1d; s/^[^:]*://g; s/, /\n/g; s/^ //' | dmenu -l 33 -h 20)
	[ -z "$selecao" ] && exit
	if [ "$selecao" = "*" ]; then
		printf "%s" "$palavra" | xclip -selection clipboard
		printf "%s" "$palavra" | xclip -selection primary
	else
		printf "%s" "$selecao" | xclip -selection clipboard
		printf "%s" "$selecao" | xclip -selection primary
	fi
	pgrep -x dunst >/dev/null && notify-send "$(xclip -o -selection clipboard) copiado."
    xdotool type --window "$window_id" "$selecao"
fi
exit
