#!/usr/bin/env bash

# Da output em caso de erro
set -euo pipefail

declare -A pesquisa

# pesquisa[engine]="https://www.google.com/search?q="
# Ferramentas de pesquisa
pesquisa[01  Google]="https://www.google.com/search?q="
pesquisa[02  Youtube]="https://www.youtube.com/results?search_query="
pesquisa[03  Github]="https://github.com/search?q="
pesquisa[04  Translate]="https://translate.google.com/?sl=auto&tl=en&text="
pesquisa[05  Soundcloud]="https://soundcloud.com/search?q="
pesquisa[06  ArchWiki]="https://wiki.archlinux.org/index.php?search="
pesquisa[07  StackExchange]="https://stackexchange.com/search?q="
pesquisa[08 שׂ Sourceforge]="https://sourceforge.net/directory/?q="
pesquisa[09  Gitlab]="https://gitlab.com/search?search="
pesquisa[10 﫴 Maps]="https://www.google.com.br/maps/search/"
pesquisa[11 念 GreasyFork]="https://greasyfork.org/en/scripts?q="

main() {
  engine=$(printf '%s\n' "${!pesquisa[@]}" | sort | dmenu -l 35 -h 20 -p 'Pesquisar com:' "$@") || exit 1
  url="${pesquisa["${engine}"]}"
  query=$(echo "$engine" | dmenu -l 11 -p "$engine")
  query="$(echo "${query}" | jq -s -R -r @uri)"
  firefox "${url}${query}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
