#!/bin/sh

case "$(printf " Bloquear\\n Resetar o sxhkd\\nﰇ Resetar o dwm\\n Sair do dwm\\nﰇ Reiniciar\\n襤 Desligar" | dmenu -l 35 -h 20 -c -cw 100 -p "Opções")" in
    " Bloquear") slock ;;
    " Resetar o sxhkd") pkill -USR1 -x sxhkd && notify-send "sxhkd reiniciado";;
    # "ﰇ Resetar o bspwm") bspc wm -r ;;
    # " Sair do bspwm") bspc quit ;;
    "ﰇ Resetar o dwm") kill -HUP "$(pgrep -u "$USER" "\bdwm$")" ;;
    " Sair do dwm") kill -TERM "$(pgrep -u "$USER" "\bdwm$")" ;;
    "ﰇ Reiniciar") systemctl reboot ;;
	"襤 Desligar") systemctl poweroff ;;
esac
