#!/bin/sh

tocando=$(deadbeef --nowplaying-tf '%filename%')
volume=$(amixer -D pulse sget Master | awk -F 'Left:|[][]' 'BEGIN {RS=""}{ print $3 }')

case "$(printf "\\n\\n\\n\\n\\n\\n玲\\n\\n怜\\n\\n墳 %s" "$volume" | dmenu -h 30 -l 1 -g 17 -y 350 -z 1360 -n 7 -p "$tocando")" in
    "玲") deadbeef --prev ;;
    "") deadbeef --play-pause ;;
    "怜") deadbeef --next ;;
    "") deadbeef --quit ;;
    "墳 $volume") st -e pulsemixer ;;
esac
