#!/bin/sh
selecao=$(tac < "$HISTFILE" | cut -d ';' -f2 | dmenu -l 35 -h 20)
printf "%s" "$selecao" | xclip -selection clipboard && notify-send Copiado "$selecao" && xdotool type --window "$window_id" "$selecao"
